disabled_rules:
- switch_case_alignment
- trailing_whitespace

line_length: 150
type_body_length: 300
function_parameter_count: 8
file_length: 500
identifier_name:
  max_length: 60
  min_length: 1
function_body_length: 45
