name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macOS-15
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: List Xcodes
        run: ls /Applications
      - name: Force Xcode 16.4
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app
      - name: Version
        run: swift --version

      - name: Cache swift-bundler
        id: cache-swift-bundler
        uses: actions/cache@v5
        with:
          path: sbun
          key: ${{ runner.os }}-swift-bundler
      - name: Build swift-bundler
        if: steps.cache-swift-bundler.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/moreSwift/swift-bundler
          cd swift-bundler
          git checkout 6d72c4f442cc2c57c2559f3df21b3777b1d0a917
          swift build --product swift-bundler
          cp .build/debug/swift-bundler ../sbun

      - name: Build arm64
        run: |
          ./sbun bundle -c release --arch arm64
          mv "$(./sbun bundle --show-bundle-path)" DeltaClient-arm64.app
      - name: Build x86
        run: |
          ./sbun bundle -c release --arch x86_64
          mv "$(./sbun bundle --show-bundle-path)" DeltaClient-x86_64.app
      - name: Zip .app (arm64)
        run: zip -r DeltaClient-arm64.zip DeltaClient-arm64.app
      - name: Zip .app (x86_64)
        run: zip -r DeltaClient-x86_64.zip DeltaClient-x86_64.app
      - name: Upload artifact (arm64)
        uses: actions/upload-artifact@v7
        with:
          name: DeltaClient-arm64
          path: ./DeltaClient-arm64.zip
      - name: Upload artifact (x86_64)
        uses: actions/upload-artifact@v7
        with:
          name: DeltaClient-x86_64
          path: ./DeltaClient-x86_64.zip
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "5.9"
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        run: |
          cd Sources/Core
          swift build
