name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-11
    steps:
      - name: Checkout delta-client
        uses: actions/checkout@v2
      - name: Check Xcode versions
        run: ls /Applications
      - name: Force Xcode 13.2
        run: sudo xcode-select -switch /Applications/Xcode_13.2.app
      - name: Download swift-bundler
        run: |
          curl -o swift-bundler -L https://github.com/stackotter/swift-bundler/releases/download/v1.4.7/swift-bundler
          chmod +x ./swift-bundler
          cp ./swift-bundler /usr/local/bin
      - name: Build
        run: ./swift-bundler build -c release -o . -u
      - name: Zip .app
        run: zip -r DeltaClient.zip DeltaClient.app
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: DeltaClient
          path: ./DeltaClient.zip
             
